_security_logout:
    resource: security.route_loader.logout
    type: service

app_user_register:
    path: /user/register
    controller: App\Controller\UserController::register
    methods: [GET, POST]

