controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_project_edit:
    path: /projet/{id}/edit
    controller: App\Controller\ProjectController::edit
    methods: [GET, POST]

app_project_assign:
    path: /projet/{id}/assign
    controller: App\Controller\ProjectController::assign
    methods: [GET, POST]

